version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-platform-api
    ports:
      - '3003:3000'
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/stream-platform
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=3600
      - PORT=3000
      - FRONTEND_URL=https://fe.streamify.id.vn
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=https://be-api.streamify.id.vn/auth/google/callback
    networks:
      - stream-platform-network
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: stream-platform-mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=stream-platform
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - stream-platform-network
    restart: unless-stopped

networks:
  stream-platform-network:
    driver: bridge

volumes:
  mysql-data: