services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-platform-api
    ports:
      - '3003:3000'
    depends_on:
      - mysql
      - minio
      - redis
    environment:
      - DATABASE_URL=mysql://root:xinhayquendi1@mysql:3306/stream-platform
      - JWT_SECRET=taisaoanhconthuongemmai
      - JWT_EXPIRATION_TIME=3600
      - PORT=3000
      - FRONTEND_URL=https://fe.streamify.id.vn
      - GOOGLE_CLIENT_ID=596808080807-eaec2bc0e65k0ngfu98snebd013gd4kp.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=https://be-api.streamify.id.vn/auth/google/callback
      - MINIO_ENDPOINT=192.168.1.134
      - MINIO_PORT=9000
      - MINIO_PUBLIC_URL=https://minio.streamify.id.vn
      - MINIO_ACCESS_KEY=TiElnsDgxpk0SQtD9QXC
      - MINIO_SECRET_KEY=AgPyY3q5yevhKBksqsLVflqI7G40be9j8HI7Z0xe
      - MINIO_BUCKET=stream-platform
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=xinhayquendi1
      - VNPAY_TMNCODE=FCDY3ZPI
      - VNPAY_HASH_SECRET=CJ1KNUB3H3XR9QQSKAQZUU1J77L9RS2O
      - VNPAY_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - VNPAY_RETURN_URL=https://fe.streamify.id.vn/
      - VNPAY_IPN_URL=https://fe.streamify.id.vn/
    networks:
      - stream-platform-network
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: stream-platform-mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=xinhayquendi1
      - MYSQL_DATABASE=stream-platform
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - stream-platform-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: stream-platform-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ':9001' /data
    networks:
      - stream-platform-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: stream-platform-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass xinhayquendi1
    networks:
      - stream-platform-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "xinhayquendi1", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  stream-platform-network:
    driver: bridge

volumes:
  mysql-data:
  minio-data:
  redis-data:
