

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-platform-api
    ports:
      - '3003:3000'
    depends_on:
      - mysql
      - minio
    environment:
      - DATABASE_URL=mysql://root:xinhayquendi1@mysql:3306/stream-platform
      - JWT_SECRET=taisaoanhconthuongemmai
      - JWT_EXPIRATION_TIME=3600
      - PORT=3000
      - FRONTEND_URL=https://fe.streamify.id.vn
      - GOOGLE_CLIENT_ID=596808080807-eaec2bc0e65k0ngfu98snebd013gd4kp.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=https://be-api.streamify.id.vn/auth/google/callback
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=sCwqBkB2XoR250rS8zIP
      - MINIO_SECRET_KEY=IpJxEcU0TMBH4CcL5wqICW0B1W6TcbVBWcDD5Mj5
      - MINIO_BUCKET=stream-platform
    networks:
      - stream-platform-network
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: stream-platform-mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=xinhayquendi1
      - MYSQL_DATABASE=stream-platform
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - stream-platform-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: stream-platform-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ':9001' /data
    networks:
      - stream-platform-network
    restart: unless-stopped

networks:
  stream-platform-network:
    driver: bridge

volumes:
  mysql-data:
  minio-data:
